apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-staging
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/lezw-1/kubernetes-gitops
      targetRevision: staging
      path: helm/apps/frontend # Helm chart source
      helm:
        valueFiles:
          - $values/envs/staging/frontend.yaml # Env-specific overrides
    - repoURL: https://github.com/lezw-1/kubernetes-gitops
      targetRevision: staging
      ref: values # Second source aliased so the path above can reference $values

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-system-staging

  syncPolicy:
    syncOptions:
      - CreateNamespace=true # Auto-create the destination namespace
    managedNamespaceMetadata:
      labels:
        team: gateway-1 # Required for HTTPRoutes to attach to the shared gateway
